name: servant-starter

dependencies:
  - base
  - warp
  - aeson
  - wai-make-assets
  - servant-elm
  - elm-export
  - servant
  - wai
  - servant-server
  - transformers
  - containers
  - persistent
  - persistent-template
  - persistent-sqlite
  - text
  - monad-logger
  - string-conversions

executables:
  server:
    main: Main.hs
    source-dirs:
      - server/src
      - server/app

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - server/test
      - server/src
    dependencies:
      - warp >= 3.2.3
      - hspec
      - servant-client
      - http-client
      - http-types
